baseURL: "https://westley-winks.github.io/"
languageCode: "en-us"
title: "Westley Winks"
theme: "./.."
relativeURLs: true

Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: "/images/fav.png"
  description: "description"

  # Navbar Menus

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Westley Winks"
  namecolor: ffc107
  profession: "Aspiring Data Scientist and Humanitarian"
  github: "https://github.com/Westley-Winks"

  # About
  disable_about: false
  disable_about_button: true
  descripe_l1_person: "Hi, I'm Westley. I love people and humanity. My mission in life is to get people access to basic needs like food, water, shelter, and equity. I want to use data to accomplish that."
  descripe_l2_person: "After graduating from Oregon State University with a Bachelor’s in Chemical Engineering, I moved to Central Oregon and was patiently waiting to leave for the Peace Corps when COVID hit and delayed those plans. Instead, I searched for a career path that led me towards my mission and found it in the field of data. I took a course in data analytics and truly loved it. I pitched a data analytics job to a local non-profit in my area and was hired as a data analyst, an opening they had never considered. I am continually learning and have a full pipeline of project ideas and courses to practice my data skills. I know that I can use data for good (actual good, not just a buzzword) and use my abilities to really help people."
  skills:
    - name: Python
      percentage: 75
    - name: R
      percentage: 75
    - name: Git
      percentage: 90

  # Experience
  disable_experience: false
  experience:
    - company: "Shiloh Ranch Church"
      id: "data-analyst"
      role: "Data Analyst"
      startdate: June 2021
      enddate: Present
      featuredpoints:
        - point: Collect and analyze data from social media platforms using API's and pandas

    - company: "HP"
      id: "reliability-intern"
      role: "Reliability Engineering Intern"
      startdate: June 2020
      enddate: April 2020
      featuredpoints:
        - point: Extracted and analyzed public weather data to inform engineering teams on what conditions products see during shipping

  # Education
  disable_education: false
  education:
    - degree: "Bachelor's of Science"
      branch: "Chemical Engineering"
      university: "Oregon State University"
      startedyear: "2017"
      graduation: "2021"

  # Projects
  disable_projects: false
  projects:
    - name: "2020 Oregon Food Insecurity Analysis"
      img: /images/oregon-food-insecurity.png
      githublink: "https://github.com/Westley-Winks/oregon-food-insecurity"
      featuredlink: "https://westley-winks.github.io/oregon-food-insecurity/"
      description: "An analysis of food insecurity in Oregon in 2020"
    - name: "Advent of Code 2021"
      img: /images/project.jpg
      githublink: "https://github.com/Westley-Winks/2021_advent-of-code"
      description: "Fun coding puzzles delivered advent style for the month of December"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Google Data Analytics
      description: 8-course data analytics specialization offered by Google
      img: /images/google-cert.png
      url: https://www.coursera.org/account/accomplishments/professional-cert/YG2SF9SZ38ME

  # Contact
  disable_contact: false
  contact_content: My communication channels are open to all. Feel free to email anytime for anything!
  email: "westleywinks@protonmail.com"

  # Why
  disable_why: false
  why_content: Here is some content! Get inspiration from that one Medium article "data guy"


  # Footer
  socialiconfooter: true
  recentposts: false
