baseURL: "https://westleywinks.com"
languageCode: "en-us"
title: "Westley Winks"
theme: "./.."
relativeURLs: true

Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: "/images/w-fav-smaller.png"
  description: "description"
  logo: "/images/w-fav.png"

  # Navbar Menus

  # home
  disable_home: false
  profile_image: "/images/me.jpeg"
  name: "Westley Winks"
  namecolor: ffc107
  profession: "Data Scientist and Aspiring Humanitarian"
  github: "https://github.com/Westley-Winks"

  # About
  disable_about: false
  disable_about_button: true
  descripe_l1_person: "Hi, I'm Westley. I am a data scientist."
  descripe_l2_person: "After graduating with a B.S. in Chemical Engineering, I thought deeply about my career goals and if engineering was a part of it. I thought about what classes I enjoyed and what parts of my internship experience at HP engaged me the most. It all pointed towards data science and I vigorously followed this new found passion."
  descripe_l3_person: "Math and chemical engineering theory were my favorite courses in college. It absolutely fascinates me that we can make computers and machines do things like drive vehicles, recognize faces, and even simpler examples like recognize hand-written digits all by using math and open source coding tools. It is also incredibly exciting that the tools are already out there, waiting to be learned and utilized."
  descripe_l4_person: "In a span of about 3 months, I completed two certifications to gain basic data science and machine learning knowledge while completing projects at the same time. I took a debt of knowledge in the form of just getting the minimum basics of the theory while focusing my efforts on the application of data science. I learned how to use the tools to create impact while intentionally forgoing learning how the tools are made. This is a debt that I am actively paying back and I am pursuing projects and resources to fill in these gaps."
  descripe_l5_person: "As data science, machine learning, and artificial intelligence are relatively new fields, it means there is ample opportunity for continual learning as I progress further down this path. Continual learning is one of my core values and a career that gives me the space to do that is exactly what I am looking for. This passion and tenacity for learning is what allowed me to quickly pivot into this field."
  descripe_l6_person: "My long term career goal is to use data science for good in a humanitarian sense. I want to be on the cutting edge of using these tools to create positive impact in the world with the knowledge that I gain."


  skills:
    - name: Python (pandas, numpy, matplotlib, sklearn, tensorflow)
      percentage: 70
    - name: R (tidyverse)
      percentage: 60
    - name: SQL (MySQL, SQLite)
      percentage: 55
    - name: Git (GitHub)
      percentage: 90
  # Experience
  disable_experience: false
  experience:
    - company: "Shiloh Ranch Church and The 1017 Project"
      id: "data-analyst"
      role: "Data Analyst"
      startdate: September 2021
      enddate: January 2022
      featuredpoints:
        - point: Collected and analyzed data from social media platforms extracted from API's with Python
        - point: Generated data visualizations for annual impact report. Compiled these visualization into a ready to deliver report

    - company: "HP"
      id: "reliability-intern"
      role: "Reliability Engineering Intern"
      startdate: June 2020
      enddate: April 2020
      featuredpoints:
        - point: Initiated a project that will allow engineers to understand conditions that merchandise sees during shipment using a global database of public weather data
        - point: Extracted and analyzed public weather data using Python

  # Education
  disable_education: false
  education:
    - degree: "Bachelor's of Science"
      branch: "Chemical Engineering"
      university: "Oregon State University"
      gpa: "3.79"
      honors: "Magna Cum Laude"
      startedyear: "2017"
      graduation: "2021"

  # Projects
  # add some kind of rollover feature when too many projects
  disable_projects: false
  projects:
    - name: "Solar Panel Energy Output Prediction"
      img: /images/solar-output.png
      tools_used: "Python, pandas, scikit-learn, requests"
      category: "Machine Learning, Regression"
      githublink: "https://github.com/Westley-Winks/solar-output"
      featuredlink: "https://share.streamlit.io/westley-winks/solar-output/main"
      description: "Predicting actual solar panel energy output using machine learning"
    - name: "2020 Oregon Food Insecurity Analysis"
      img: /images/oregon-food-insecurity.png
      tools_used: "R, tidyverse"
      category: "Data Analysis"
      githublink: "https://github.com/Westley-Winks/oregon-food-insecurity"
      featuredlink: "https://westley-winks.github.io/oregon-food-insecurity/"
      description: "An analysis of food insecurity in Oregon in 2020"

    # - name: "2021 Portland Crime Analysis"
    #   img: /images/portland-crime-map.png
    #   tools_used: "Python, geopandas, pandas"
    #   category: "Data Analysis"
    #   githublink: "https://github.com/Westley-Winks/john-crime"
    #   featuredlink: "https://westley-winks.github.io/john-crime/"
    #   description: "An analysis into crime in key neighborhoods around my friend's house in Portland, Oregon"

  # Certifications
  disable_achievements: false
  achievements:
    - title: Google Data Analytics Certificate
      description: 8-course data analytics specialization certificate offered by Google. Courses included data cleaning, EDA, visualization, storytelling with data, and R language.
      img: /images/google-cert.png
      url: https://www.coursera.org/account/accomplishments/professional-cert/YG2SF9SZ38ME

    - title: 365 Data Science - Data Scientist Career Track
      description: 10-course certificate track for data science hosted by 365 Data Science. Courses include deep learning, convolutional neural networks, machine learning, SQL, Python, and foundational skills such as probability and statistics.
      img: /images/365-certification.jpg
      url: https://learn.365datascience.com/c/0b53e0749a/

  # Contact
  disable_contact: false
  contact_content: My communication channels are open to all. Feel free to email anytime for anything!
  email: "westleywinks@protonmail.com"

  # Why
  disable_why: true
  why_content: Here is some content!

  # Footer
  socialiconfooter: true
  recentposts: false
